name: renjani
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.1 <4.0.0'

dependencies: 
  #Base
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: ^2.0.3
  google_fonts: ^4.0.3
  dio: ^5.0.3
  flutter_screenutil: ^5.7.0
  jwt_decoder: ^2.0.1
  package_info_plus: ^3.0.1
  intl: ^0.17.0
  carousel_slider: ^4.0.0
  dropdown_button2: ^2.1.3
  flutter_svg: ^2.0.7
  flutter_widget_from_html_core: ^0.10.1
  font_awesome_flutter: ^10.4.0
  flutter_staggered_grid_view: ^0.6.2
  fluttertoast: ^8.2.2
  image_picker: ^1.0.0
  shimmer: ^3.0.0
  lazy_load_scrollview: 1.3.0
  # internet cek
  internet_connection_checker: ^1.0.0+1
  # login finger
  local_auth: ^2.1.6

  #test
  cached_network_image: ^3.2.3
  

  flutter: 
    sdk: flutter
  permission_handler: ^10.4.2
  flutter_swipe_action_cell: ^3.1.2
  smooth_page_indicator: ^1.1.0
  expandable_page_view: ^1.0.17
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.12.0

flutter_launcher_name:
  name: "Renjani DJP"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_app_blue.png"
  min_sdk_android: 16


flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
   

